-- Create custom types
create type public.tournament_mode as enum ('CS', 'BR');
create type public.tournament_subtype as enum ('SOLO', 'DUO', 'SQUAD', '1V1', '2V2', '4V4', '6V6');
create type public.tournament_status as enum ('DRAFT', 'PUBLISHED', 'COMPLETED', 'CANCELLED');
create type public.ticket_status as enum ('PENDING_PAYMENT', 'PAID', 'CANCELLED', 'KICKED');
create type public.player_type as enum ('RUSHER', 'SNIPER', 'NGL', 'GRANADER');

-- Create Players table
create table public.players (
    id uuid not null references auth.users on delete cascade,
    ff_uid bigint not null unique,
    name text not null,
    mobile text not null unique,
    player_type player_type,
    ff_id_level integer,
    years_experience integer,
    upi_qr_code_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    primary key (id)
);
alter table public.players enable row level security;
create policy "Players can view their own profile." on public.players for select using (auth.uid() = id);
create policy "Players can update their own profile." on public.players for update using (auth.uid() = id);

-- Create Admins table
create table public.admins (
    id uuid not null references auth.users on delete cascade,
    mobile text not null unique,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    primary key (id)
);
alter table public.admins enable row level security;
create policy "Admins can see all admins" on public.admins for select using (exists (select 1 from public.admins where id = auth.uid()));

-- Create Tournaments table
create table public.tournaments (
    id bigint generated by default as identity primary key,
    title text not null,
    thumbnail_url text,
    mode tournament_mode not null,
    subtype tournament_subtype not null,
    max_players integer not null,
    entry_fee integer not null default 0,
    start_time timestamp with time zone not null,
    rules text,
    prize_distribution jsonb,
    status tournament_status not null default 'DRAFT',
    room_id text,
    room_pass text,
    created_by uuid references public.admins(id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.tournaments enable row level security;
create policy "Anyone can view published tournaments." on public.tournaments for select using (status = 'PUBLISHED');
create policy "Admins can manage tournaments." on public.tournaments for all using (exists (select 1 from public.admins where id = auth.uid()));

-- Create Tickets table
create table public.tickets (
    id uuid primary key default gen_random_uuid(),
    tournament_id bigint not null references public.tournaments on delete cascade,
    player_id uuid not null references public.players on delete cascade,
    status ticket_status not null default 'PENDING_PAYMENT',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique (tournament_id, player_id)
);
alter table public.tickets enable row level security;
create policy "Players can see their own tickets." on public.tickets for select using (player_id = auth.uid());
create policy "Admins can see all tickets." on public.tickets for select using (exists (select 1 from public.admins where id = auth.uid()));
create policy "Ticket holders can see room details of their tournament." on public.tournaments for select using (
    id in (select tournament_id from public.tickets where player_id = auth.uid() and status = 'PAID')
);

-- Create Winners table
create table public.winners (
    id bigint generated by default as identity primary key,
    tournament_id bigint not null references public.tournaments on delete cascade,
    player_id uuid not null references public.players on delete cascade,
    rank integer not null,
    kills integer,
    damage integer,
    game_duration_seconds integer,
    prize_amount integer,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.winners enable row level security;
create policy "Anyone can view winners." on public.winners for select using (true);
create policy "Admins can create winners." on public.winners for insert with check (exists (select 1 from public.admins where id = auth.uid()));


-- Create Transactions table (for payouts)
create table public.transactions (
    id bigint generated by default as identity primary key,
    winner_id bigint not null references public.winners on delete cascade,
    amount integer not null,
    transaction_id text, -- Manual transaction ID from GPay/PhonePe
    paid_by uuid not null references public.admins(id),
    paid_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.transactions enable row level security;
create policy "Admins and relevant winner can see transactions." on public.transactions for select using (
    (exists (select 1 from public.admins where id = auth.uid())) OR
    (winner_id in (select id from public.winners where player_id = auth.uid()))
);
create policy "Admins can create transactions." on public.transactions for insert with check (exists (select 1 from public.admins where id = auth.uid()));

-- Create Global Chat table
create table public.global_chat (
    id bigint generated by default as identity primary key,
    sender_id uuid not null references public.players on delete cascade,
    message text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.global_chat enable row level security;
create policy "Authenticated users can read global chat." on public.global_chat for select using (auth.role() = 'authenticated');
create policy "Players can send messages." on public.global_chat for insert with check (sender_id = auth.uid());

-- Create Tournament Chat table
create table public.tournament_chat (
    id bigint generated by default as identity primary key,
    tournament_id bigint not null references public.tournaments on delete cascade,
    sender_id uuid not null references public.players on delete cascade,
    message text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.tournament_chat enable row level security;
create policy "Tournament participants can read chat." on public.tournament_chat for select using (
    (exists (select 1 from public.admins where id = auth.uid())) OR
    (tournament_id in (select tournament_id from public.tickets where player_id = auth.uid() and status = 'PAID'))
);
create policy "Tournament participants can send messages." on public.tournament_chat for insert with check (
    tournament_id in (select tournament_id from public.tickets where player_id = auth.uid() and status = 'PAID')
);

-- Create Audit Logs table
create table public.audit_logs (
    id bigint generated by default as identity primary key,
    actor_id uuid,
    action text not null,
    target_id text,
    details jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.audit_logs enable row level security;
create policy "Admins can view audit logs." on public.audit_logs for select using (exists (select 1 from public.admins where id = auth.uid()));

-- Enable realtime on tables
alter publication supabase_realtime add table public.tournaments, public.tickets, public.global_chat, public.tournament_chat;

-- Configure storage buckets
insert into storage.buckets (id, name, public) values ('thumbnails', 'thumbnails', true);
insert into storage.buckets (id, name, public) values ('qrcodes', 'qrcodes', false);

create policy "Admins can upload thumbnails." on storage.objects for insert to authenticated with check ( bucket_id = 'thumbnails' AND (select id from public.admins where id = auth.uid()) is not null );
create policy "Anyone can see thumbnails" on storage.objects for select using ( bucket_id = 'thumbnails' );

create policy "Players can view their own QR code." on storage.objects for select using ( bucket_id = 'qrcodes' AND owner = auth.uid() );
create policy "Players can upload their own QR code." on storage.objects for insert with check ( bucket_id = 'qrcodes' AND owner = auth.uid() );
create policy "Players can update their own QR code." on storage.objects for update using ( bucket_id = 'qrcodes' AND owner = auth.uid() );
create policy "Players can delete their own QR code." on storage.objects for delete using ( bucket_id = 'qrcodes' AND owner = auth.uid() );

create policy "Admins can see QR codes." on storage.objects for select using ( bucket_id = 'qrcodes' AND (select id from public.admins where id = auth.uid()) is not null );